const express = require('express')
const { registerUser, allUser, addFriend, loginUser, showFriend } = require('../controller/user.js')
const { middleware, tokenValidate } = require('../middleware/middleware.js')
exports.userRoute = express.Router()
    .post('/register-user', express.json(), registerUser)
    .get('/all-users', middleware, allUser)
    .post('/add-friend', express.json(), middleware, addFriend)
    .post('/login-user', express.json(), loginUser)
    .get('/my-friend', middleware, showFriend)
    .get('/token',express.json(),tokenValidate)